version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
    depends_on:
      - db
    restart: always

  db:
    image: nouchka/sqlite:latest
    volumes:
      - ./db:/data
    environment:
      - SQLITE_DATABASE_URL=/data/test.db
    restart: always
